name: artifact-upload
version: 1.0.0
icon: "upload.svg"

inputs:
- name: FLOWCI_JOB_ARTIFACT_PATH
  type: string
  required: true

script: |
  plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/artifact-upload
  python3 ${plugindir}/src/upload.py