name: artifact-upload
version: 1.0.0
icon: "upload.svg"

inputs:
- name: artifact.path
  type: string
  required: false

- name: artifact.pattern
  type: string
  required: false

script: |
  plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/artifact-upload
  cd ${FLOWCI_GIT_REPO}

  if [[ -n ${artifact.path} ]]; then
    python3 ${plugindir}/src/upload.py ${artifact.path}
  fi

  if [[ -n ${artifact.pattern} ]]; then
    found=$(find . -type f -name "${artifact.pattern}")
    python3 ${plugindir}/src/upload.py ${found} 
  fi